[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "Cython>=0.28.5",
    "numpy @ git+https://github.com/colesbury/numpy.git@v1.19.3-nogil",
    "scipy @ git+https://github.com/colesbury/scipy.git@v1.7.1-nogil",
]
